require 'cgi'

module Spectate
  # A convenience module to provide URI-safe versions of spectator names.  It essentially
  # just uses URI::Escape on the strings, but with the additional conversion of spaces to
  # underscores (and underscores to double underscores) because having lots of '%20' blobs
  # in a URL is painful on the eyes. 
  module Encode
    # Makes a name URI-safe, with the minor cosmetic tweak of underscoring spaces.
    def encode(name)
      name.gsub!(/_/,'__')
      name.tr!(' ','_')
      CGI::escape(name)
    end
    
    # Turns a URI-safe name generated by 'encode' back into a reasonable string.
    def decode(name)
      name.gsub!(/_(?!_)/,' ')
      name.gsub!(/_ /,'_')
      CGI::unescape(name)
    end
  end
end